name: Publish NuGet Package

on:
  push:
    branches:
      - main

jobs:
  build-and-publish:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: '10.*' # Ensures the latest .NET 10 preview is used
        cache: true

    - name: Restore dependencies
      run: dotnet restore src/Pikot.DDD/Pikot.DDD/Pikot.DDD.csproj

    - name: Build project
      run: dotnet build src/Pikot.DDD/Pikot.DDD/Pikot.DDD.csproj --configuration Release

    - name: Pack project
      run: dotnet pack src/Pikot.DDD/Pikot.DDD/Pikot.DDD.csproj --configuration Release --output ./output

    - name: Publish to NuGet
      env:
        NUGET_API_KEY: ${{ secrets.NUGET_API_KEY }}
      run: dotnet nuget push ./output/*.nupkg --api-key $NUGET_API_KEY --source https://api.nuget.org/v3/index.json